// Generated by pnpm localization:generate from localization.config.json.
import ar from "./ar.json";
import ca from "./ca.json";
import cs from "./cs.json";
import da from "./da.json";
import de from "./de.json";
import el from "./el.json";
import en from "./en.json";
import es from "./es.json";
import esMX from "./es-MX.json";
import fi from "./fi.json";
import fr from "./fr.json";
import frCA from "./fr-CA.json";
import he from "./he.json";
import hr from "./hr.json";
import hu from "./hu.json";
import id from "./id.json";
import it from "./it.json";
import ja from "./ja.json";
import ko from "./ko.json";
import ms from "./ms.json";
import nb from "./nb.json";
import nl from "./nl.json";
import pl from "./pl.json";
import ptBR from "./pt-BR.json";
import ptPT from "./pt-PT.json";
import ro from "./ro.json";
import ru from "./ru.json";
import sk from "./sk.json";
import sl from "./sl.json";
import sv from "./sv.json";
import th from "./th.json";
import tr from "./tr.json";
import uk from "./uk.json";
import vi from "./vi.json";
import zhHans from "./zh-Hans.json";
import zhHant from "./zh-Hant.json";

export const catalogs: Record<string, Record<string, string>> = {
  ar: ar,
  ca: ca,
  cs: cs,
  da: da,
  de: de,
  el: el,
  en: en,
  es: es,
  "es-MX": esMX,
  fi: fi,
  fr: fr,
  "fr-CA": frCA,
  he: he,
  hr: hr,
  hu: hu,
  id: id,
  it: it,
  ja: ja,
  ko: ko,
  ms: ms,
  nb: nb,
  nl: nl,
  pl: pl,
  "pt-BR": ptBR,
  "pt-PT": ptPT,
  ro: ro,
  ru: ru,
  sk: sk,
  sl: sl,
  sv: sv,
  th: th,
  tr: tr,
  uk: uk,
  vi: vi,
  "zh-Hans": zhHans,
  "zh-Hant": zhHant,
};
