// Generated by pnpm localization:generate from localization.config.json.
import de from "./de.json";
import en from "./en.json";
import es from "./es.json";
import esMX from "./es-MX.json";
import fr from "./fr.json";
import frCA from "./fr-CA.json";
import ja from "./ja.json";
import ko from "./ko.json";
import ptBR from "./pt-BR.json";

export type SupportedLocale =
  | "de"
  | "en"
  | "es"
  | "es-MX"
  | "fr"
  | "fr-CA"
  | "ja"
  | "ko"
  | "pt-BR";

export const catalogs: Record<
  SupportedLocale,
  Record<string, string | Record<string, string>>
> = {
  de: de,
  en: en,
  es: es,
  "es-MX": esMX,
  fr: fr,
  "fr-CA": frCA,
  ja: ja,
  ko: ko,
  "pt-BR": ptBR,
};

export function isSupportedLocale(locale: string): locale is SupportedLocale {
  return Object.hasOwn(catalogs, locale);
}
