packages:
  - "apps/*"
allowBuilds:
  '@shopify/react-native-skia': true
  browser-tabs-lock: true
  bufferutil: true
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true

nodeLinker: hoisted
patchedDependencies:
  expo-dev-launcher@58.0.9: patches/expo-dev-launcher@58.0.9.patch
  expo-widgets@58.0.9: patches/expo-widgets@58.0.9.patch
